'use strict';

// ---------------------------------------------------------------------------
// Governed ADW reporting-view catalogue.
//
// This is the AI_* metadata layer described in the blueprint (§2, §4–§9):
// the ONLY objects the prompt engine, SQL guardrail and dashboard studio may
// reference. RAW_*/STG_*/CORE_* objects are intentionally absent — they are
// never exposed to the AI planner or to OAC.
// ---------------------------------------------------------------------------

export const DOMAINS = {
  SHARED: { code: 'SHARED', label: 'Shared Enterprise', color: 'series-5' },
  FIN: { code: 'FIN', label: 'Finance', color: 'series-1' },
  HCM: { code: 'HCM', label: 'HCM & Workforce', color: 'series-2' },
  SCM: { code: 'SCM', label: 'Supply Chain', color: 'series-3' },
  CX: { code: 'CX', label: 'CX & Sales', color: 'series-6' },
  XFN: { code: 'XFN', label: 'Cross-Functional', color: 'series-8' }
};

export const ROLES = [
  {
    id: 'viewer', label: 'Business Viewer',
    canCreate: false, canPublish: false, canApprove: false, canAdmin: false,
    canSeeSecure: false, canSeeAudit: false,
    note: 'View, filter, drill and ask grounded questions within approved dashboards.'
  },
  {
    id: 'analyst', label: 'Functional Analyst',
    canCreate: true, canPublish: true, canApprove: false, canAdmin: false,
    canSeeSecure: false, canSeeAudit: false,
    note: 'Create dashboard drafts within the authorised domain; submit for OAC publication.'
  },
  {
    id: 'steward', label: 'Data Steward',
    canCreate: true, canPublish: false, canApprove: true, canAdmin: false,
    canSeeSecure: false, canSeeAudit: false,
    note: 'Maintain glossary, view definitions, hierarchies and drill-path metadata.'
  },
  {
    id: 'approver', label: 'Dashboard Approver',
    canCreate: false, canPublish: false, canApprove: true, canAdmin: false,
    canSeeSecure: false, canSeeAudit: false,
    note: 'Review business value, layout, security and ownership; approve shared OAC releases.'
  },
  {
    id: 'admin', label: 'Platform Administrator',
    canCreate: true, canPublish: true, canApprove: true, canAdmin: true,
    canSeeSecure: true, canSeeAudit: true,
    note: 'Manage connections, environments, templates, roles and logs. Actions audited.'
  },
  {
    id: 'audit', label: 'Internal Control / Audit',
    canCreate: false, canPublish: false, canApprove: false, canAdmin: false,
    canSeeSecure: false, canSeeAudit: true,
    note: 'Read-only monitoring of prompts, SQL history, approvals and security exceptions.'
  }
];

export const DRILL_HIERARCHIES = [
  { id: 'org', label: 'Organisation', route: ['Group / Cluster', 'Legal Entity', 'Company', 'Business Unit', 'Department / Cost Centre', 'Location'] },
  { id: 'time', label: 'Time', route: ['Year', 'Quarter', 'Month', 'Week', 'Day'] },
  { id: 'account', label: 'Financial account', route: ['Account Class', 'Natural Account Group', 'Natural Account', 'Cost Centre', 'Journal / Subledger'] },
  { id: 'customer', label: 'Customer', route: ['Customer Group', 'Customer Account', 'Site', 'Transaction / Receipt / Opportunity'] },
  { id: 'supplier', label: 'Supplier', route: ['Category', 'Supplier', 'Site', 'PO', 'Receipt', 'Invoice', 'Payment'] },
  { id: 'item', label: 'Item / logistics', route: ['Product Category', 'Item', 'Inventory Organisation', 'Transaction / Order', 'Shipment'] },
  { id: 'workforce', label: 'Workforce', route: ['Legal Employer', 'Business Unit', 'Department', 'Grade', 'Position', 'Worker'] }
];

// Each view is a reporting contract (§2.2): purpose, grain, lineage, refresh,
// owner, permitted roles, measures, dimensions and its drill hierarchy.
export const VIEWS = [
  // ---- Shared enterprise (§4) ----
  { name: 'RPT_DIM_DATE_V', domain: 'SHARED', secure: false, refresh: 'Daily 02:00', owner: 'Enterprise Data Office',
    grain: 'One row per calendar date with fiscal calendar, accounting period, week, month, quarter, year, prior-period flags and working-day markers.',
    measures: [], dims: ['fiscal_year', 'quarter', 'accounting_period_name', 'week', 'calendar_date'], drill: 'time' },
  { name: 'RPT_DIM_ENTERPRISE_ORG_V', domain: 'SHARED', secure: false, refresh: 'Daily 02:00', owner: 'Enterprise Data Office',
    grain: 'One row per cluster, legal entity, company, business unit, department, cost centre and location relationship, effective-dated.',
    measures: [], dims: ['cluster_name', 'company_name', 'business_unit_name', 'department_name', 'cost_center_name', 'location_name'], drill: 'org' },
  { name: 'RPT_DIM_ACCOUNT_COMBINATION_V', domain: 'SHARED', secure: false, refresh: 'Daily 02:00', owner: 'Group Finance',
    grain: 'One row per chart-of-accounts combination with company, natural account, cost centre, location, product/project, intercompany and future segment.',
    measures: [], dims: ['natural_account_code', 'natural_account_name', 'cost_center_code', 'account_class'], drill: 'account' },
  { name: 'RPT_DIM_CURRENCY_RATE_V', domain: 'SHARED', secure: false, refresh: 'Daily 02:00', owner: 'Group Treasury',
    grain: 'One row per currency, rate type, rate date and reporting currency conversion.',
    measures: ['conversion_rate'], dims: ['currency_code', 'rate_type', 'rate_date'], drill: 'time' },
  { name: 'RPT_DIM_CUSTOMER_360_V', domain: 'SHARED', secure: false, refresh: 'Daily 03:00', owner: 'CX Data Owner',
    grain: 'One row per customer account/site with hierarchy, industry, geography, credit profile and ownership.',
    measures: [], dims: ['customer_group', 'customer_name', 'site_name', 'industry', 'geography'], drill: 'customer' },
  { name: 'RPT_DIM_SUPPLIER_360_V', domain: 'SHARED', secure: false, refresh: 'Daily 03:00', owner: 'Procurement Data Owner',
    grain: 'One row per supplier/site with category, status, bank-data sensitivity flag, business unit and procurement ownership.',
    measures: [], dims: ['supplier_category', 'supplier_name', 'site_name', 'status'], drill: 'supplier' },
  { name: 'RPT_DIM_ITEM_360_V', domain: 'SHARED', secure: false, refresh: 'Daily 03:00', owner: 'SCM Data Owner',
    grain: 'One row per item, item category, UOM, status, planner, inventory organisation and product hierarchy.',
    measures: [], dims: ['item_category_name', 'item_number', 'item_description', 'uom', 'planner'], drill: 'item' },
  { name: 'SEC_DIM_WORKER_V', domain: 'SHARED', secure: true, refresh: 'Daily 04:00', owner: 'HR Data Owner',
    grain: 'Secure worker dimension with employee, assignment, role, manager, department and effective-dated attributes. Applies row access and masks sensitive personal fields.',
    measures: [], dims: ['legal_employer_name', 'department_name', 'grade_name', 'position_name', 'worker_name'], drill: 'workforce' },
  { name: 'RPT_DATA_FRESHNESS_V', domain: 'SHARED', secure: false, refresh: 'Each extract batch', owner: 'Enterprise Data Office',
    grain: 'One row per source domain, extract batch, reporting view and refresh status.',
    measures: ['refresh_age_hours', 'quality_score'], dims: ['source_domain', 'reporting_view', 'batch_id', 'refresh_status'], drill: 'time' },
  { name: 'RPT_ENTERPRISE_KPI_DAILY_V', domain: 'SHARED', secure: false, refresh: 'Daily 05:00', owner: 'Group CFO Office',
    grain: 'One row per enterprise, company, business unit and day with approved cross-functional KPIs.',
    measures: ['revenue_amt', 'operating_cost_amt', 'cash_balance_amt', 'headcount', 'otif_pct', 'pipeline_amt'], dims: ['company_name', 'business_unit_name', 'calendar_date'], drill: 'org' },

  // ---- Finance (§5) ----
  { name: 'RPT_FIN_GL_BALANCE_PERIOD_V', domain: 'FIN', secure: false, refresh: 'Daily 05:00', owner: 'Group Financial Controller',
    grain: 'One row per ledger, company, accounting period, currency and account combination showing opening, movement and closing balance.',
    measures: ['opening_balance_amt', 'period_debit_amt', 'period_credit_amt', 'closing_balance_amt', 'budget_amt', 'budget_variance_amt'],
    dims: ['fiscal_year', 'accounting_period_name', 'cluster_name', 'company_name', 'business_unit_name', 'cost_center_name', 'natural_account_name', 'ledger_currency_code'], drill: 'account' },
  { name: 'RPT_FIN_GL_JOURNAL_LINE_V', domain: 'FIN', secure: false, refresh: 'Daily 05:00', owner: 'Group Financial Controller',
    grain: 'One row per posted journal line with accounting date, source, category, preparer, approval/status and supporting reference.',
    measures: ['entered_debit_amt', 'entered_credit_amt', 'accounted_debit_amt', 'accounted_credit_amt'],
    dims: ['accounting_date', 'journal_source', 'journal_category', 'preparer', 'approval_status', 'company_name', 'natural_account_name'], drill: 'account' },
  { name: 'RPT_FIN_BUDGET_VS_ACTUAL_V', domain: 'FIN', secure: false, refresh: 'Daily 05:00', owner: 'Group FP&A',
    grain: 'One row per budget version, period, organisation and account combination with actual, budget, forecast and variance.',
    measures: ['actual_amt', 'budget_amt', 'forecast_amt', 'variance_amt', 'variance_pct'],
    dims: ['budget_version', 'accounting_period_name', 'company_name', 'cost_center_name', 'natural_account_name'], drill: 'account' },
  { name: 'RPT_FIN_AP_INVOICE_PAYMENT_V', domain: 'FIN', secure: false, refresh: 'Daily 05:30', owner: 'Shared Services AP',
    grain: 'One row per supplier invoice/payment relationship with PO, receipt, invoice, approval, due date, payment and ageing status.',
    measures: ['invoice_amt', 'paid_amt', 'discount_amt', 'days_to_pay'],
    dims: ['supplier_name', 'invoice_number', 'po_number', 'due_date', 'payment_status', 'company_name'], drill: 'supplier' },
  { name: 'RPT_FIN_AP_AGEING_V', domain: 'FIN', secure: false, refresh: 'Daily 05:30', owner: 'Shared Services AP',
    grain: 'One row per open AP invoice at reporting date with ageing bucket, due date and payment-hold status.',
    measures: ['outstanding_amt', 'overdue_amt'],
    dims: ['ageing_bucket', 'supplier_name', 'company_name', 'payment_hold_flag', 'due_date'], drill: 'supplier' },
  { name: 'RPT_FIN_AR_TRANSACTION_RECEIPT_V', domain: 'FIN', secure: false, refresh: 'Daily 05:30', owner: 'Shared Services AR',
    grain: 'One row per receivables transaction/receipt application with customer, invoice, due date, collection status and receipt date.',
    measures: ['billed_amt', 'open_amt', 'collected_amt', 'unapplied_amt', 'dispute_amt'],
    dims: ['customer_name', 'invoice_number', 'due_date', 'collection_status', 'company_name'], drill: 'customer' },
  { name: 'RPT_FIN_AR_AGEING_V', domain: 'FIN', secure: false, refresh: 'Daily 05:30', owner: 'Shared Services AR',
    grain: 'One row per open AR item at reporting date with bucket, collector, credit status and collection promise.',
    measures: ['open_amt', 'overdue_amt', 'dso_days'],
    dims: ['ageing_bucket', 'customer_name', 'collector', 'credit_status', 'company_name'], drill: 'customer' },
  { name: 'RPT_FIN_CASH_DAILY_POSITION_V', domain: 'FIN', secure: false, refresh: 'Daily 06:00', owner: 'Group Treasury',
    grain: 'One row per bank account, company, currency and date with opening, inflow, outflow, closing and forecast cash.',
    measures: ['opening_cash_amt', 'inflow_amt', 'outflow_amt', 'closing_cash_amt', 'forecast_cash_amt'],
    dims: ['bank_name', 'bank_account', 'company_name', 'currency_code', 'calendar_date'], drill: 'org' },
  { name: 'RPT_FIN_BANK_RECON_EXCEPTION_V', domain: 'FIN', secure: false, refresh: 'Daily 06:00', owner: 'Group Treasury',
    grain: 'One row per bank statement/reconciliation exception or unreconciled cash item.',
    measures: ['exception_amt', 'exception_age_days'],
    dims: ['bank_name', 'statement_ref', 'reconciliation_status', 'company_name'], drill: 'org' },
  { name: 'RPT_FIN_FIXED_ASSET_V', domain: 'FIN', secure: false, refresh: 'Monthly close', owner: 'Group Financial Controller',
    grain: 'One row per asset/book/period showing cost, depreciation, net book value, location, custodian and status.',
    measures: ['additions_amt', 'depreciation_amt', 'disposals_amt', 'nbv_amt'],
    dims: ['asset_category', 'asset_number', 'book_name', 'location_name', 'custodian', 'status'], drill: 'org' },
  { name: 'RPT_FIN_EXPENSE_COMPLIANCE_V', domain: 'FIN', secure: false, refresh: 'Daily 06:00', owner: 'Shared Services AP',
    grain: 'One row per expense report/line with employee, policy, exception, approver and reimbursement status.',
    measures: ['claimed_amt', 'exception_count', 'cycle_time_days'],
    dims: ['department_name', 'policy_name', 'exception_type', 'approver', 'reimbursement_status'], drill: 'org' },
  { name: 'RPT_FIN_TAX_TRANSACTION_V', domain: 'FIN', secure: false, refresh: 'Daily 06:00', owner: 'Group Tax',
    grain: 'One row per taxable transaction/tax line with tax regime, rate, recoverability and accounting period.',
    measures: ['taxable_base_amt', 'tax_amt', 'recoverable_tax_amt'],
    dims: ['tax_regime', 'tax_rate', 'accounting_period_name', 'company_name'], drill: 'account' },
  { name: 'RPT_FIN_PROJECT_FINANCIALS_V', domain: 'FIN', secure: false, refresh: 'Daily 06:00', owner: 'PMO',
    grain: 'One row per project/task/period where Project Management is enabled.',
    measures: ['revenue_amt', 'cost_amt', 'budget_amt', 'commitment_amt', 'margin_amt'],
    dims: ['project_name', 'task_name', 'accounting_period_name', 'company_name'], drill: 'org' },

  // ---- HCM (§6) ----
  { name: 'RPT_HCM_WORKFORCE_SNAPSHOT_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'HR Data Owner',
    grain: 'One row per effective employee assignment at an as-of date, with organisation, manager, grade, position, worker type and employment status.',
    measures: ['headcount', 'fte', 'vacancy_count', 'contingent_count'],
    dims: ['legal_employer_name', 'business_unit_name', 'department_name', 'grade_name', 'position_name', 'worker_type', 'assignment_status'], drill: 'workforce' },
  { name: 'RPT_HCM_WORKFORCE_MOVEMENT_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'HR Data Owner',
    grain: 'One row per hire, transfer, promotion, termination, assignment or organisation movement event.',
    measures: ['joiners', 'leavers', 'transfers', 'movement_rate', 'time_to_fill_days'],
    dims: ['event_type', 'legal_employer_name', 'department_name', 'calendar_date'], drill: 'workforce' },
  { name: 'RPT_HCM_ORG_SPAN_CONTROL_V', domain: 'HCM', secure: false, refresh: 'Weekly', owner: 'HR Data Owner',
    grain: 'One row per manager/organisation/time period with team size, layers, vacancy and manager span.',
    measures: ['span_of_control', 'management_layers', 'vacancy_count'],
    dims: ['legal_employer_name', 'department_name', 'manager_name'], drill: 'workforce' },
  { name: 'RPT_HCM_ABSENCE_ACCRUAL_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'HR Data Owner',
    grain: 'One row per absence/accrual event and worker/plan/date, with entitlement, taken, adjustment and balance.',
    measures: ['entitlement_days', 'taken_days', 'balance_days', 'absence_rate_pct'],
    dims: ['absence_plan', 'legal_employer_name', 'department_name', 'calendar_date'], drill: 'workforce' },
  { name: 'SEC_HCM_PAYROLL_COST_V', domain: 'HCM', secure: true, refresh: 'Monthly payroll run', owner: 'Head of Reward',
    grain: 'Secure monthly payroll and employer-cost summary by legal employer, department, grade and cost centre. Payroll drill restricted to authorised roles.',
    measures: ['gross_pay_amt', 'employer_cost_amt', 'deductions_amt', 'cost_variance_amt'],
    dims: ['legal_employer_name', 'department_name', 'grade_name', 'cost_center_name', 'accounting_period_name'], drill: 'workforce' },
  { name: 'RPT_HCM_RECRUITMENT_PIPELINE_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'Head of Talent Acquisition',
    grain: 'One row per requisition/candidate stage/time period where Recruiting is enabled.',
    measures: ['open_requisitions', 'candidates', 'stage_conversion_pct', 'time_to_fill_days', 'offer_acceptance_pct'],
    dims: ['job_family', 'stage_name', 'requisition_number', 'legal_employer_name'], drill: 'workforce' },
  { name: 'RPT_HCM_PERFORMANCE_TALENT_V', domain: 'HCM', secure: true, refresh: 'Review cycle', owner: 'Head of Talent',
    grain: 'One row per worker performance/talent review cycle where Talent is enabled. Secure drill by authorised role.',
    measures: ['completion_pct', 'rating_distribution', 'succession_coverage_pct', 'overdue_reviews'],
    dims: ['review_cycle', 'legal_employer_name', 'department_name'], drill: 'workforce' },
  { name: 'RPT_HCM_LEARNING_COMPLIANCE_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'Head of Learning',
    grain: 'One row per assigned learning record, course, due date, completion date and compliance status.',
    measures: ['completion_pct', 'overdue_count', 'assigned_count'],
    dims: ['course_name', 'company_name', 'department_name', 'compliance_status', 'due_date'], drill: 'workforce' },
  { name: 'SEC_HCM_COMPENSATION_V', domain: 'HCM', secure: true, refresh: 'Compensation cycle', owner: 'Head of Reward',
    grain: 'Secure compensation and compensation-change summary where Compensation is enabled. HR/leadership access only.',
    measures: ['salary_movement_pct', 'comp_range_penetration', 'exception_count'],
    dims: ['legal_employer_name', 'grade_name', 'department_name'], drill: 'workforce' },
  { name: 'RPT_HCM_WORKFORCE_DATA_QUALITY_V', domain: 'HCM', secure: false, refresh: 'Daily 04:30', owner: 'HR Data Owner',
    grain: 'One row per worker/assignment record requiring HR data attention.',
    measures: ['issue_count'],
    dims: ['issue_type', 'legal_employer_name', 'department_name'], drill: 'workforce' },

  // ---- SCM (§7) ----
  { name: 'RPT_SCM_REQUISITION_CYCLE_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Procurement',
    grain: 'One row per requisition line with requester, category, buyer, approval stage, required date and conversion status.',
    measures: ['req_cycle_time_days', 'approval_ageing_days', 'conversion_rate_pct'],
    dims: ['business_unit_name', 'supplier_category', 'buyer', 'approval_stage', 'requisition_number'], drill: 'supplier' },
  { name: 'RPT_SCM_PO_COMMITMENT_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Procurement',
    grain: 'One row per PO line/schedule with supplier, item/category, commitment, receipt, invoice and remaining commitment.',
    measures: ['committed_amt', 'received_amt', 'invoiced_amt', 'open_po_amt'],
    dims: ['supplier_name', 'item_category_name', 'po_number', 'business_unit_name'], drill: 'supplier' },
  { name: 'RPT_SCM_RECEIPT_MATCH_EXCEPTION_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Procurement',
    grain: 'One row per receipt or three-way-match exception with PO, supplier, receiving date and exception reason.',
    measures: ['exception_amt', 'exception_age_days'],
    dims: ['exception_reason', 'supplier_name', 'po_number', 'business_unit_name'], drill: 'supplier' },
  { name: 'RPT_SCM_SUPPLIER_PERFORMANCE_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Procurement',
    grain: 'One row per supplier/site/category/period based on PO, receipt and quality/exception measures.',
    measures: ['on_time_delivery_pct', 'lead_time_days', 'price_variance_pct', 'rejection_rate_pct'],
    dims: ['supplier_name', 'site_name', 'supplier_category', 'accounting_period_name'], drill: 'supplier' },
  { name: 'RPT_SCM_SPEND_ANALYSIS_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Procurement',
    grain: 'One row per supplier, category, buyer, business unit and period spend allocation.',
    measures: ['spend_amt', 'supplier_concentration_pct', 'off_contract_amt', 'price_trend_pct'],
    dims: ['supplier_category', 'supplier_name', 'buyer', 'business_unit_name', 'accounting_period_name'], drill: 'supplier' },
  { name: 'RPT_SCM_INVENTORY_POSITION_DAILY_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Supply Chain',
    grain: 'One row per inventory organisation, subinventory, item and date with opening, receipts, issues, transfers, adjustments and closing.',
    measures: ['on_hand_quantity', 'available_quantity', 'reserved_quantity', 'inventory_value_amt', 'days_of_supply'],
    dims: ['business_unit_name', 'inventory_org_name', 'item_category_name', 'item_number', 'calendar_date'], drill: 'item' },
  { name: 'RPT_SCM_INVENTORY_TRANSACTION_V', domain: 'SCM', secure: false, refresh: 'Hourly', owner: 'Head of Supply Chain',
    grain: 'One row per inventory material transaction with transaction type, item, organisation, source and reference.',
    measures: ['transaction_quantity', 'transaction_value_amt'],
    dims: ['transaction_type', 'item_number', 'inventory_org_name', 'source_reference'], drill: 'item' },
  { name: 'RPT_SCM_STOCKOUT_RISK_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Supply Chain',
    grain: 'One row per item/org/date evaluating available stock, demand, reorder point, lead time and projected coverage.',
    measures: ['days_of_supply', 'stockout_risk_score', 'excess_risk_score'],
    dims: ['item_category_name', 'item_number', 'inventory_org_name', 'business_unit_name'], drill: 'item' },
  { name: 'RPT_SCM_ITEM_VELOCITY_V', domain: 'SCM', secure: false, refresh: 'Weekly', owner: 'Head of Supply Chain',
    grain: 'One row per item/org/period measuring demand frequency, movement velocity and inactive-stock periods.',
    measures: ['fast_moving_count', 'slow_moving_count', 'non_moving_count', 'value_at_risk_amt'],
    dims: ['item_category_name', 'item_number', 'inventory_org_name', 'velocity_class'], drill: 'item' },
  { name: 'RPT_SCM_COST_MARGIN_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Supply Chain',
    grain: 'One row per item/order/period where costing and order data are enabled.',
    measures: ['unit_cost_amt', 'sales_value_amt', 'margin_amt', 'cost_variance_amt'],
    dims: ['item_number', 'order_number', 'accounting_period_name'], drill: 'item' },
  { name: 'RPT_SCM_ORDER_FULFILMENT_V', domain: 'SCM', secure: false, refresh: 'Hourly', owner: 'Head of Logistics',
    grain: 'One row per customer order line with promised, scheduled, shipped, delivered and invoiced dates/status.',
    measures: ['otif_pct', 'fulfilment_cycle_days', 'backlog_amt', 'cancellation_rate_pct'],
    dims: ['customer_name', 'order_number', 'line_status', 'business_unit_name'], drill: 'customer' },
  { name: 'RPT_SCM_SHIPMENT_DELIVERY_V', domain: 'SCM', secure: false, refresh: 'Hourly', owner: 'Head of Logistics',
    grain: 'One row per shipment/delivery detail with carrier, destination, ship date, delivery date and exception.',
    measures: ['on_time_delivery_pct', 'transit_days', 'exception_count'],
    dims: ['carrier', 'destination', 'shipment_number', 'exception_type'], drill: 'item' },
  { name: 'RPT_SCM_MAINTENANCE_WORK_ORDER_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Maintenance',
    grain: 'One row per maintenance work order/asset/time period where Maintenance is enabled.',
    measures: ['open_work_orders', 'backlog_age_days', 'downtime_hours', 'completion_pct', 'maintenance_cost_amt'],
    dims: ['asset_number', 'work_order_number', 'inventory_org_name'], drill: 'item' },
  { name: 'RPT_SCM_MANUFACTURING_PRODUCTION_V', domain: 'SCM', secure: false, refresh: 'Daily 05:00', owner: 'Head of Manufacturing',
    grain: 'One row per work order/operation/item/period where Manufacturing is enabled.',
    measures: ['planned_output', 'actual_output', 'yield_pct', 'scrap_pct', 'cycle_time_days'],
    dims: ['plant_name', 'item_number', 'work_order_number'], drill: 'item' },

  // ---- CX (§8) ----
  { name: 'RPT_CX_CUSTOMER_360_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'CX Data Owner',
    grain: 'One row per customer account/site/period enriched with sales, receivables, order, service and ownership context where available.',
    measures: ['revenue_amt', 'open_ar_amt', 'order_value_amt', 'opportunity_value_amt'],
    dims: ['customer_group', 'customer_name', 'site_name', 'accounting_period_name'], drill: 'customer' },
  { name: 'RPT_CX_LEAD_FUNNEL_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'Head of Sales Operations',
    grain: 'One row per lead/stage/date/owner with source, campaign, qualification and conversion status.',
    measures: ['lead_volume', 'conversion_rate_pct', 'lead_age_days'],
    dims: ['lead_source', 'campaign', 'sales_owner_name', 'stage_name'], drill: 'customer' },
  { name: 'RPT_CX_OPPORTUNITY_PIPELINE_SNAPSHOT_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'Head of Sales Operations',
    grain: 'One row per opportunity snapshot date with stage, amount, probability, forecast category, close date and sales owner.',
    measures: ['opportunity_amount', 'weighted_pipeline_amt', 'expected_revenue_amt', 'days_in_stage', 'days_since_last_activity'],
    dims: ['cluster_name', 'business_unit_name', 'sales_owner_name', 'sales_stage_name', 'forecast_category_name', 'close_date'], drill: 'customer' },
  { name: 'RPT_CX_OPPORTUNITY_ACTIVITY_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'Head of Sales Operations',
    grain: 'One row per opportunity activity/task/interaction where activity data is available.',
    measures: ['activity_coverage_pct', 'days_since_activity', 'action_completion_pct'],
    dims: ['sales_owner_name', 'opportunity_number', 'activity_type'], drill: 'customer' },
  { name: 'RPT_CX_FORECAST_ACCURACY_V', domain: 'CX', secure: false, refresh: 'Weekly', owner: 'Head of Sales Operations',
    grain: 'One row per sales period/business unit/owner comparing committed, best-case, pipeline and actual outcomes.',
    measures: ['forecast_variance_pct', 'attainment_pct', 'forecast_bias_pct'],
    dims: ['accounting_period_name', 'business_unit_name', 'sales_owner_name'], drill: 'customer' },
  { name: 'RPT_CX_WIN_LOSS_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'Head of Sales Operations',
    grain: 'One row per closed opportunity with outcome, competitor, loss reason, value and cycle duration.',
    measures: ['win_rate_pct', 'sales_cycle_days', 'closed_value_amt'],
    dims: ['outcome', 'competitor', 'loss_reason', 'sales_owner_name', 'customer_name'], drill: 'customer' },
  { name: 'RPT_CX_SALES_OWNER_PERFORMANCE_V', domain: 'CX', secure: false, refresh: 'Daily 06:00', owner: 'Head of Sales Operations',
    grain: 'One row per sales owner/period with opportunity coverage, activity, conversion and closed value.',
    measures: ['attainment_pct', 'win_rate_pct', 'pipeline_coverage_ratio', 'cycle_time_days'],
    dims: ['territory', 'sales_owner_name', 'accounting_period_name'], drill: 'customer' },
  { name: 'RPT_CX_CUSTOMER_EXPANSION_V', domain: 'CX', secure: false, refresh: 'Weekly', owner: 'CX Data Owner',
    grain: 'One row per customer/period identifying cross-sell, upsell, renewal and whitespace indicators where defined.',
    measures: ['expansion_value_amt', 'recurring_opportunity_amt', 'customer_growth_pct'],
    dims: ['customer_name', 'accounting_period_name', 'expansion_type'], drill: 'customer' },
  { name: 'RPT_CX_SERVICE_CASE_V', domain: 'CX', secure: false, refresh: 'Hourly', owner: 'Head of Service',
    grain: 'One row per service request/case where Service is enabled.',
    measures: ['open_cases', 'sla_attainment_pct', 'resolution_age_days'],
    dims: ['customer_name', 'case_number', 'severity', 'status'], drill: 'customer' },

  // ---- Cross-functional (§9) ----
  { name: 'RPT_XFN_ORDER_TO_CASH_V', domain: 'XFN', secure: false, refresh: 'Daily 06:30', owner: 'Group CFO Office',
    grain: 'One row per customer order/invoice/receipt lifecycle with customer, order, shipment, invoice and collection milestones.',
    measures: ['order_value_amt', 'fulfilment_days', 'billed_amt', 'collection_days', 'dispute_amt'],
    dims: ['customer_name', 'order_number', 'invoice_number', 'company_name'], drill: 'customer' },
  { name: 'RPT_XFN_PROCURE_TO_PAY_V', domain: 'XFN', secure: false, refresh: 'Daily 06:30', owner: 'Group CFO Office',
    grain: 'One row per requisition-to-payment lifecycle linking requester, supplier, PO, receipt, invoice and payment.',
    measures: ['cycle_time_days', 'commitment_amt', 'exception_count', 'days_to_pay'],
    dims: ['supplier_name', 'po_number', 'invoice_number', 'business_unit_name'], drill: 'supplier' },
  { name: 'RPT_XFN_CASH_CONVERSION_CYCLE_V', domain: 'XFN', secure: false, refresh: 'Monthly close', owner: 'Group Treasury',
    grain: 'One row per company/period with DSO, DPO, inventory days and cash-conversion-cycle components.',
    measures: ['dso_days', 'dpo_days', 'inventory_days', 'ccc_days'],
    dims: ['company_name', 'accounting_period_name'], drill: 'org' },
  { name: 'RPT_XFN_REVENUE_MARGIN_CUSTOMER_V', domain: 'XFN', secure: false, refresh: 'Daily 06:30', owner: 'Group CFO Office',
    grain: 'One row per customer/item/business unit/period joining revenue, cost, fulfilment and payment context.',
    measures: ['revenue_amt', 'margin_amt', 'ar_exposure_amt', 'order_cycle_days'],
    dims: ['customer_name', 'item_number', 'business_unit_name', 'accounting_period_name'], drill: 'customer' },
  { name: 'RPT_XFN_WORKFORCE_COST_PRODUCTIVITY_V', domain: 'XFN', secure: false, refresh: 'Monthly close', owner: 'Group CFO Office',
    grain: 'One row per company/department/period with HCM headcount/FTE and approved Finance cost data.',
    measures: ['cost_per_fte_amt', 'revenue_per_fte_amt', 'overtime_signal', 'absence_signal'],
    dims: ['company_name', 'department_name', 'accounting_period_name'], drill: 'org' },
  { name: 'RPT_XFN_ENTERPRISE_RISK_SIGNAL_V', domain: 'XFN', secure: false, refresh: 'Daily 06:30', owner: 'Group Risk',
    grain: 'One row per business entity/period/risk type, combining approved financial, operational, workforce and sales indicators.',
    measures: ['risk_score', 'materiality_amt'],
    dims: ['company_name', 'risk_type', 'risk_owner', 'trend'], drill: 'org' },
  { name: 'RPT_XFN_DATA_QUALITY_SCORECARD_V', domain: 'XFN', secure: false, refresh: 'Each extract batch', owner: 'Enterprise Data Office',
    grain: 'One row per data domain/view/batch with completeness, validity, timeliness and reconciliation status.',
    measures: ['quality_score', 'failed_checks', 'refresh_age_hours'],
    dims: ['data_domain', 'reporting_view', 'batch_id', 'reconciliation_status'], drill: 'org' },
  { name: 'RPT_XFN_ACCESS_AUDIT_V', domain: 'XFN', secure: true, refresh: 'Continuous', owner: 'Internal Control',
    grain: 'One row per access/change/approval action for analytics governance and system control. Restricted audit drill.',
    measures: ['event_count', 'failed_events'],
    dims: ['event_type', 'actor', 'target_object', 'event_date'], drill: 'org' }
];

export const VIEW_INDEX = new Map(VIEWS.map((v) => [v.name, v]));

// Sensitive columns rejected by the guardrail regardless of view (§12.3).
export const SENSITIVE_COLUMNS = [
  'salary', 'national_id', 'bank_account_number', 'iban', 'tax_id',
  'date_of_birth', 'home_address', 'personal_email', 'personal_phone',
  'remuneration', 'compensation_amount'
];

// OAC template library (§11.1) — approved catalog paths and named visual zones.
export const OAC_TEMPLATES = [
  { id: 'fin-exec', label: 'Finance Executive Template', domain: 'FIN', catalogPath: '/Shared Folders/Custom/Finance/Executive' },
  { id: 'fin-working-capital', label: 'Working Capital & Cash Template', domain: 'FIN', catalogPath: '/Shared Folders/Custom/Finance/WorkingCapital' },
  { id: 'hcm-workforce', label: 'Workforce Executive Template', domain: 'HCM', catalogPath: '/Shared Folders/Custom/HCM/Workforce' },
  { id: 'scm-p2p', label: 'Procure-to-Pay Control Tower Template', domain: 'SCM', catalogPath: '/Shared Folders/Custom/SCM/ProcureToPay' },
  { id: 'scm-inventory', label: 'Inventory Availability & Risk Template', domain: 'SCM', catalogPath: '/Shared Folders/Custom/SCM/Inventory' },
  { id: 'cx-pipeline', label: 'Sales Pipeline Command Centre Template', domain: 'CX', catalogPath: '/Shared Folders/Custom/CX/Pipeline' },
  { id: 'xfn-command', label: 'Group Command Centre Template', domain: 'XFN', catalogPath: '/Shared Folders/Custom/Enterprise/CommandCentre' }
];

// Curated prompt library (§14.1) surfaced in the Ask workspace.
export const PROMPT_LIBRARY = [
  { domain: 'FIN', text: 'Show year-to-date revenue, operating cost and gross margin by company, with a monthly trend and drill-down to cost centre and natural account.' },
  { domain: 'FIN', text: 'Which suppliers account for the largest overdue payables balance, and which invoices are beyond agreed payment terms?' },
  { domain: 'FIN', text: 'Explain the drivers of the June expense variance against budget for the Nigeria business unit.' },
  { domain: 'FIN', text: 'Show daily cash position by bank and company, forecast the next 30 days and highlight balances below the approved threshold.' },
  { domain: 'HCM', text: 'Show current headcount, FTE, hires, exits and vacancy rate by legal employer and department, with a trend for the last 12 months.' },
  { domain: 'HCM', text: 'Explain why payroll cost increased this month by business unit, grade and cost centre. Do not display employee-level remuneration.' },
  { domain: 'SCM', text: 'Show procurement spend by category and supplier for the year, highlight supplier concentration and allow drill-down to purchase order, receipt and invoice.' },
  { domain: 'SCM', text: 'Which inventory items are at risk of stockout in the next 30 days, and which business units will be affected?' },
  { domain: 'CX', text: 'Show the sales pipeline by cluster, business unit and stage, including weighted value, forecast category and close-date risk.' },
  { domain: 'CX', text: 'Show forecast accuracy for the past six months and identify sales teams with repeated forecast bias.' },
  { domain: 'XFN', text: 'Show the cash conversion cycle by company and identify whether receivables, payables or inventory is driving the movement.' },
  { domain: 'XFN', text: 'Compare revenue per FTE and workforce cost per FTE by business unit and identify outliers requiring management review.' }
];
